name: eczanem
description: A new Flutter project for Medicine Tracking.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  uuid: ^3.0.7
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.5
  google_fonts: ^6.1.0
  path_provider: ^2.0.15 # Useful for hive on mobile

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
